### ISSUE TITLE
Problem mapping telegram / influxdb

### ISSUE THREAD

**Issue by hulzer** [c1328/ahoy-mosquitto-telegraf-influx-grafana#1]
Hello,
thank you for your effort.

I am having problems getting the system to work.

I have configured Telegraf as in your example, I have set this mapping: [https://github.com/lumapu/ahoy/issues/517#issuecomment-1382729683](https://github.com/lumapu/ahoy/issues/517#issuecomment-1382729683)

At first I had the problem that Telegraf reported a 404 because it did not find the bucket - I then created a database in InfluxDb and specified it as a bucket in Telegraf.

Now data has been created, but unfortunately the selects in Grafana do not match the whole structure.

Am I doing something wrong here?

"pv" is the MQTT topic, the inverter runs under "HM-600".

![image](https://user-images.githubusercontent.com/27423823/220204656-2864f58f-2b77-461b-b1f2-3ecd8f83ed20.png)
![image](https://user-images.githubusercontent.com/27423823/220204715-203b2119-8ea1-4eed-88a3-5b4fda333e1b.png)
![image](https://user-images.githubusercontent.com/27423823/220204800-b81beebc-bcbe-42d2-a972-4a8cee00bfb0.png)

[pv.csv](https://github.com/c1328/ahoy-mosquitto-telegraf-influx-grafana/files/10788027/pv.csv)

Maybe you can help me?
Thank you

**Comment by c1328** [comment]
Hi!
First thing is to check if you configured the variables in the dashboard accordingly:
<img width="788" alt="image" src="https://user-images.githubusercontent.com/112856305/220439367-6f426719-c4e8-4fd8-be13-e23ca9b72cc5.png">

Some difficulties exists with the mapping of "name" because your total values are mapped to "total" and all others to "HM-600" and this dashboard version was never intended to work with to inverter (screenshot is from a newer version).

My recommendation is - if you want to stick to that mapping - create one more variable, e.g. with name "total" with the value "total" and than go to the panels that show "total" values and change the variable $inverterName to $total in the query.

**Comment by hulzer** [comment]
Hi!

My variables look like that:
![image](https://user-images.githubusercontent.com/27423823/220441626-8d5d924c-62c6-46b3-81e3-ef13e4c79bf9.png)

My question is, what's the default mapping that your dashboard works out of the box?

**Comment by c1328** [comment]
Hi!
Default of this version is
ahoyTopic = inverter
ahoyInvertername = Hoymiles

And I did not used the parsing, my mqtt config was just:
``` servers = [“tcp://localhost:1883”]
topics = [ “ahoyTopic/#” ]
qos = 0
connection_timeout = “30s”
username = “USERNAME”
password = “PASSWORD”
data_format = “value”
data_type = “float”

**Comment by hulzer** [comment]
How does your [[outputs.influxdb_v2]] section look like?

I had to set a bucket name otherwise I got a 404....

**Comment by c1328** [comment]
Hi!
If you have Influx 2.x in use, queries look total different. This version was never in use with influx 2.x but I have a newer version that is based on Influx 2.x - but it is also based on ioBroker. But maybe it helps you to get an idea how the queries have to be transformed to work with Influx 2.x -> https://github.com/c1328/ahoy-iobroker-influx-grafana
